application.user.user:
    resource: '@ApplicationProjectUserBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.admin.admin:
    resource: '@ApplicationAdminBundle/Resources/config/routes/routes.yaml'
    prefix: /

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check