# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'pt_BR'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

#    app.menu_listener:
#        class: App\Application\Project\AdminBundle\EventListener\MenuBuilderListener
#        tags:
#            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
#        arguments:
    # Project Services

#    admin.custom:
#        class: App\Admin\CustomAdmin
#        tags:
#            - { name: sonata.admin, model_class: App\Entity\Custom, manager_type: orm, label: Category, security_handler: App\Application\Project\AdminBundle\Security\Handler }



    app.controller.user:
        class: App\Application\Project\UserBundle\Controller\UserApiController
        arguments:
            - '@lexik_jwt_authentication.jwt_manager'

    admin.user:
        class: App\Application\Project\UserBundle\Admin\UserAdmin
        #arguments: [ ~ , App\Application\Project\UserBundle\Entity\User, App\Application\Project\UserBundle\Controller\UserAdminController ]
        #arguments: [ App\Application\Project\AdminBundle\Service , '@security.user_authenticator' ]
        tags:
            #- { name: sonata.admin, manager_type: orm, group: "Autenticação", label: User, on_top: false, icon: 'fa fa-solid fa-user' }
            - { name: sonata.admin, manager_type: orm, model_class: App\Application\Project\UserBundle\Entity\User, controller: App\Application\Project\UserBundle\Controller\UserAdminController, group: "Autenticação", label: Usuario, on_top: false, icon: 'fa fa-solid fa-user', show_in_dashboard: true  }

    admin.group:
        class: App\Application\Project\UserBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_class: App\Application\Project\UserBundle\Entity\Group, controller: App\Application\Project\UserBundle\Controller\GroupAdminController, group: "Autenticação", label: Grupo, on_top: false, icon: 'fa fa-solid fa-user', show_in_dashboard: true }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.documento:
        class: App\Admin\DocumentoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, model_class: App\Entity\Documento, group: "Documentos", label: Documento, on_top: false, icon: 'fa fa-solid fa-user', show_in_dashboard: true }
